name: 'check book image format'
description: 'check book image format'
author: 'srz-zumix'

inputs:
  path:
    description: |
      image directory path.
      default is '.'
    default: .
    required: false
  level:
    description: |
      report level (warning or error).
      default is 'error'
    default: "error"
    required: false
  dpi:
    description: |
      require dpi.
      if dpi==0, skip this check.
      default is '350'
    default: "350"
    required: false
  longside:
    description: |
      min longside pixel.
      if longside==0, skip this check.
      default is '1000'
    default: "1000"
    required: false
  pixel_limit:
    description: |
      maximum pixels.
      if pixel_limit==0, skip this check.
      default is '4000000'
    default: "4000000"
    required: false
  formats:
    description: |
      require formats (comma sparate).
      if empty, skip this check.
      default is 'JPEG'
    default: 'JPEG'
    required: false
  always_success:
    description: |
      always exit code 0.
      default is 'false'
    default: "false"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.level }}
    - ${{ inputs.dpi }}
    - ${{ inputs.longside }}
    - ${{ inputs.pixel_limit }}
    - ${{ inputs.formats }}
    - ${{ inputs.exit_code_0 }}
branding:
  icon: 'image'
  color: 'green'
